### ISSUE TITLE
Hi! When will the code be released? Thanks!

### ISSUE THREAD

**Issue by DLwbm123** [DequanWang/tent#2]

**Comment by AI678** [comment]
same question

**Comment by shelhamer** [comment]
Please try out our [example](https://github.com/DequanWang/tent#example-adapting-to-image-corruptions-on-cifar-10-c) and [tent module](https://github.com/DequanWang/tent/blob/master/tent.py)! We released the example code at commit dc0ac07, and will follow up with more.

**Comment by AI678** [comment]
So , what kind of model arc was used  in your paper ? It seems that model arc 'Standard' can not reproduce your CIFAR-10-C results 
claimed in the paper.
